SCREEN 9
LOCATE 1, 1
PRINT "Player One";
LOCATE 1, 68
PRINT "Player Two";
LOCATE 2, 1
PRINT "Angle:";
LOCATE 3, 1
PRINT "Velocity:";
LOCATE 12, 26
PRINT "Q B a s i c   G O R I L L A S";
LOCATE 23, 36
PRINT "0>Score<0";
LOCATE 25, 1
PRINT "abcdefghijklmnopqrstuvwxyz0123456789.,:;!?()[]<>+-*/=_";
LOCATE 20, 5
PRINT "Underscore cursor: 45_";
LOCATE 21, 5
PRINT "*    *    *    *    *";
DO
LOOP UNTIL INKEY$ <> ""
SYSTEM
